### ISSUE TITLE
Browse by reaction: no heading, or nothing listed below the heading

### ISSUE THREAD

**Issue by grahamperrin** [moritzjacobs/github-tada#2]
Home-built Waterfox Classic 56.2.14 on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/66249559-21e96800-e72d-11e9-8264-94c135a0718f.png)

Firefox Quantum: 

![image](https://user-images.githubusercontent.com/192271/66249568-49403500-e72d-11e9-92e2-0712ebb99d36.png)

Tested at: 

- https://github.com/MrAlex94/Waterfox/issues/267#issue-273890196

**Comment by moritzjacobs** [comment]
Thank you for bringing this to my attention. Is there anything suspicious going on in the error console?

**Comment by moritzjacobs** [comment]
Also is there another addon that puts the avatars in the reactions? Maybe that messes something up.

**Comment by grahamperrin** [comment]
> another addon that puts the avatars in the reactions? 

I tested with a different profile, github-tada alone enabled. 

When a page first loaded – _maybe_ after disabling all other extensions – there was an array of rectangles close to the `#show_issue` part of the page. 

After a reload without cache e.g. <kbd>Control</kbd>-<kbd>F5</kbd> the rectangles became populated: 

![image](https://user-images.githubusercontent.com/192271/66364287-17bfa780-e981-11e9-8f79-e37845381d1a.png)

- https://github.com/MrAlex94/Waterfox/issues/267#show_issue

In retrospect: the **non-populated** rectangles were remarkable during a previous test, but I chose to not capture a screenshot because (in the absence of any reaction in any rectangle) I assumed that there were a glitch with some other extension. 

Reproducible with a simple reload, whilst not signed in, and now I see that each rectangle is clickable: 

![image](https://user-images.githubusercontent.com/192271/66364721-9b2dc880-e982-11e9-8387-4e3d37d52efb.png)

Reloading without the cache is not a reliable workaround for non-population of the rectangles: 

![image](https://user-images.githubusercontent.com/192271/66364913-28711d00-e983-11e9-993c-03e308ec35a9.png)

Eventually: 

![image](https://user-images.githubusercontent.com/192271/66365035-89005a00-e983-11e9-8733-203d7b4741a9.png)

**Comment by moritzjacobs** [comment]
Thank you for your input, I will see if I can reproduce these issues on the weekend.

**Comment by moritzjacobs** [comment]
It works in the corresponding Waterfox versions on macOS, I can't really reproduce the problem. Sorry... is it possible to use something like web-ext with WF?

**Comment by grahamperrin** [comment]
Apologies for the late reply … I've been getting blanks with Firefox 70, the same with 71.0. 

With github-tada alone enabled: 

![image](https://user-images.githubusercontent.com/192271/69823933-4d0aa800-1202-11ea-8353-ffe3baa79cc8.png)

**Comment by moritzjacobs** [comment]
I tried both versions on windows and macOS. I can't imagine a reason for this having OS related issues, since it is only javascript. Do you know about limitations for FF on FreeBSD?

**Comment by grahamperrin** [comment]
Hmm. I had one of these two URLs open in a tab, in very heavily extended Waterfox Classic on FreeBSD-CURRENT, for a long time: 

`https://github.com/claustromaniac/httpz/issues/37#issuecomment-560488711`

`https://github.com/claustromaniac/httpz/issues/37`

I was preparing to quit the application then noticed, for the first time since I don't know when, an array of reactions in the right-hand column. Stupidly I didn't take a screenshot. After I reloaded the page the array did not reappear. 

### Postscript

For now, ignore the two URLs above. With the heavily extended Waterfox Classic I certainly had reactions (in the right-hand column) at: 

`https://github.com/matrix-org/matrix-appservice-irc/issues/208#issuecomment-495803454`

– and after reloading the page, the reactions did not reappear. 

I tried the same URL with Firefox 71.0 with the extension in isolation, waited a while, the column of reactions did not appear. 

Screen recording saved locally. 

Weird. I'll keep a closer eye on symptoms over the next few days.

**Comment by grahamperrin** [comment]
> Do you know about limitations for FF on FreeBSD?

It's Tier-3 but I can't imagine a FreeBSD-specific explanation for this issue. 

If I look to consoles, should I use the web console alone? Or the browser console? 

Focus solely on JavaScript in the console?

**Comment by moritzjacobs** [comment]
> If I look to consoles, should I use the web console alone? Or the browser console?

Maybe both, I'm not sure.

**Comment by moritzjacobs** [comment]
I just released 2.0.0 which removes react as a dependency, maybe that solves your issue?

=> https://addons.mozilla.org/en-US/firefox/addon/github-tada/
